src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Controller\QuickRegisterController;
use App\Security\UserSession;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * Class User
 * @package App\Entity
 */
final class User implements UserInterface
{

    /** @var string $username */
    private $username;

    /** @var string|null $api_token */
    private $api_token;

    /** @var bool $claimed */
    private $claimed = false;

    ///
    ///

    /**
     * @return string|null
     */
    public function getApiToken(): ?string
    {
        return $this->api_token;
    }

    /**
     * @param string|null $api_token
     */
    public function setApiToken(?string $api_token): void
    {
        $this->api_token = $api_token;
    }

    /**
     * Returns the roles granted to the user.
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Initially returns the password used to authenticate the user.
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * But!
     * We store no password, and we do not use this in the login guard.
     * Still, the Security internals use this, amongst other to see if the User changed.
     * They check if the password changed **before** checking the username.
     * See symfony/security-core/Authentication/Token/AbstractToken.php line 312
     *
     * So, we're returning the API token if there's one.
     * We could also return a static string, perhaps?  It worked in preliminary tests.
     *
     * @return string|null The encoded password if any
     * @throws \Exception
     */
    public function getPassword()
    {
        return $this->getApiToken();
//        throw new \Exception("The method User#getPassword() was used. It should not.");
//        return 'The method getPassword() was used. It should not.';
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param string $username
     */
    public function setUsername($username): void
    {
        $this->username = $username;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        mem0($this->api_token);
        $this->api_token = null;
    }

    /**
     * Probably a bad pattern here.  UserProvider calls this.
     * @param UserSession $userSession
     */
    public function updateFromUserSession(UserSession $userSession)
    {
        $sessionUserData = $userSession->getUser();
        $this->claimed = ! ($sessionUserData[QuickRegisterController::SESSION_ONE_CLICK] ?? false);
    }

    public function isClaimed(): bool
    {
        return $this->claimed;
    }

    public function markClaimed(): void
    {
        $this->claimed = true;
    }

    /**
     * Get a clone of this User, without the API token set.
     * This is used in twig templates and translation strings,
     * who are prone to injection vulnerabilities because of their nature,
     * because we use them often to interpolate data coming from userland.
     * Therefore, it's usually best to provide them with watered-down versions of our data.
     *
     * @return $this
     */
    public function getSafeClone(): self
    {
        $user = clone $this;
        $user->setApiToken(null);
        return $user;
    }

    /**
     * @return $this
     * @deprecated
     */
    public function getWithoutToken(): self
    {
        return $this->getSafeClone();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>{% block title %}{{ 'meta.title' | trans }}{% endblock %}</title>

{% block favicons %}
        {# Generated by a GIMP script : https://github.com/lepisma/gimp-export-favicons -#}
{% block favicons_generic %}
        <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="/favicon-128x128.png" sizes="128x128" />
{% endblock %}
{% block favicons_vendor %}
        {# The following is platform-specific clutter ; remove eventually  -#}
        <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
        <meta name="application-name" content="{{ 'meta.title' | trans }}" />
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
        <meta name="msapplication-square70x70logo" content="/mstile-70x70.png" />
        <meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />
        <meta name="msapplication-wide310x150logo" content="/mstile-310x150.png" />
        <meta name="msapplication-square310x310logo" content="/mstile-310x310.png" />
{% endblock %}
{% endblock %}

{% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
{% endblock %}
{% block stylesheets_extra %}{% endblock %}
{% block opengraph %}{% endblock %}
    </head>
    <body>
{% block body %}

{% block header %}
    <header class="navbar bg-primary">
        <section class="navbar-section">
            <nav>
                <a
                        href="{{ path('home') }}"
                        class="with-image tooltip tooltip-right"
                        aria-label="{{ 'action.home.label' | trans }}"
                        title="{{ 'action.home.title' | trans }}"
                        data-tooltip="{{ 'action.home.title' | trans }}"
                >
                    <img
                            src="/mv-logo.svg"
                            alt="Mieux Voter"
                            width="40"
                            height="40"
                            style="filter: invert(1); vertical-align: middle;"
                    >
                </a>
            </nav>
        </section>
        {# QUICK-ACCESS USER PROFILE WIDGET #}
        {# The fact that this section is in the header is annoying for TTS browsers. #}
        {# Perhaps this should be moved to the bottom, and only displayed visually at the top via CSS. #}
        {# If we do that, it's the whole header navbar that should move to the bottom perhaps.  #}
        {# Tricky subject ; am still undecided.  Help?  #}
        {# We want the navbar to be at the bottom in semantics, but at the top in visual browsers. #}
        {# It's annoying having to cycle through it, yet we can configure the initial focus per page #}
        {# lynx does not understand our way of setting the focus, though. #}
        <section class="navbar-section">
            <nav>
{% if app.user %}
                <span>
                    {{ 'nav.auth.logged_in_as.label' | trans({ 'user': app.user.safeClone }) }}

                    {# Claim the current user, if it was registered in one-click. #}
                    {# It's the second step in a two-steps registration, sort of. #}
                    {% if not app.user.isClaimed %}
                    <a
                            href="{{ path('claim_user_html', {'redirect': app.request.requesturi}) }}"
{#                            class="btn btn-primary"#}
                            title="{{ 'action.claim.title' | trans }}"
                    >
                        {{ 'action.claim.label' | trans }}
                    </a>
                    {% endif %}

                    <a
                            href="{{ path('logout') }}"
                    >
                        ({{ 'nav.auth.logout.label' | trans }})
                    </a>
                </span>
{% else %}
                <a
                        href="{{ path('login_html', {'redirect': app.request.requesturi}) }}"
                        class="btn btn-primary"
                        title="{{ 'action.login.title' | trans }}"
                >
                    {{ 'action.login.label' | trans }}
                </a>
{% endif %}{# app.user #}
            </nav>
        </section>
    </header>
{% endblock %}{# header #}

{% block flash_messages %}
{% include "partials/flash_messages.html.twig" only %}
{% endblock %}

{% block main_container_wrapper %}
    <div class="content main container grid-lg breathe-top {% block main_container_class %}{% endblock %}">
{% block main_container %}{% endblock %}
    </div>
{% endblock %}{# main_container_wrapper #}

{% endblock %}{# body #}

{% block footer %}
    <footer>
        <div class="columns">
            <div class="column col-6 text-center justify-content-evenly">
                <a href="https://mieuxvoter.fr">MieuxVoter</a>
                &copy; 2020
            </div>
            <div class="column col-6 text-center justify-content-evenly">
                <a
                        class="version"
                        href="https://github.com/MieuxVoter/mv-api-client-symfony4"
                        title="Version number of the software.!"
                >
                    v{{ shivas_app_version }} (alpha)
                </a>
                <br>
                <span class="license">
                    AGPL-3.0-or-later
                </span>
            </div>
        </div>
    </footer>
{% endblock %}{# footer #}

{# There's no client-side javascript for now #}
{# Rule: this client must work in CLI browsers -- that means no js #}
{% block javascripts %}{% endblock %}
    </body>
</html>